### ISSUE TITLE
KeyError:x['labels']

### ISSUE THREAD

**Issue by YjwHello** [YoumiMa/dreeam#1]
[作者您好，感谢您所做的工作。在跑代码时我遇到了上面的问题，我觉得是不是图片上的代码有问题，因为test.json文件没有label标签，而official_evaluate这个函数是要处理label标签的]
![image](https://user-images.githubusercontent.com/48909484/223442179-ae51a503-dba5-4c02-9485-e5eab0c1f94e.png)

**Comment by YoumiMa** [comment]
@YjwHello 您好，感谢您的提问！
我已在commit`ab18aa0`中修改了代码，希望能解决您的问题。
请注意[DocRED](https://github.com/thunlp/DocRED)的`test.json`文件的正确标签是未公开的。要获取在该文件上的正确分数，请将模型生成的预测文件（`results.json`, `fused_results.json`）按要求上传至[官方网站](https://codalab.lisn.upsaclay.fr/competitions/365)。谢谢！

**Comment by YjwHello** [comment]
感谢您的回复，对我很有帮助

**Comment by YjwHello** [comment]
我直接运行run.py，结果显示0
![image](https://user-images.githubusercontent.com/48909484/223488356-8f442679-b8e9-47c9-bbae-4ac4289d88b4.png)

**Comment by YoumiMa** [comment]
@YjwHello 可以麻烦提供一下您用来运行代码的bash script的内容吗？谢谢！

**Comment by YjwHello** [comment]
![image](https://user-images.githubusercontent.com/48909484/223606383-d9277b1d-440c-4931-9018-f95f37089873.png)
作者，您好，这是run_bert.sh的内容，上面是我直接运行的run.py文件，如果用bash文件跑的话，会出现下面的错误
![image](https://user-images.githubusercontent.com/48909484/223609898-a738f14d-a9db-4752-9ee7-c27a5b481807.png)

**Comment by YoumiMa** [comment]
@YjwHello 您好，感谢您的回复！

首先，关于run_bert.sh的报错，基于您提供的截图，我推测您的测试环境是windows。由于本项目的测试环境为linux/unix，并未在windows系统上做过充分的测试，于windows系统上运行本项目可能会存在一些问题。我在最新的commit(`432fb46`)中修改了一部分代码，希望能够解决这一报错。如果问题仍未解决，请尝试安装[wsl](https://learn.microsoft.com/en-us/windows/wsl/install)或linux/unix系统。

其次，关于您直接运行run.py文件，验证集上显示分数为0的问题，请确保您是否向run.py传递了必要且正确的参数（可以参考run_bert.sh），尤其是`--do_train`。如果您没有向run.py传递`--do_train`这一参数，那么代码将返回未经训练的测试结果。此外，请确保您向run.py传递了正确的训练集与验证集的路径。

希望能对您有帮助，谢谢！

**Comment by YjwHello** [comment]
感谢您的详细回复，后面我会根据您的意见进行修改
