### ISSUE TITLE
The code of Heatmaps

### ISSUE THREAD

**Issue by edwarddiou** [YoumiMa/dreeam#10]
Hi , I am interested in your research. 
May i ask about the code of heatmaps in the end of the paper ? 
I cant find it in the NCRF++.    

Thanks a lot

**Comment by YoumiMa** [comment]
Hi @edwarddiou, thanks for your interest in this project, and sorry for the late reply.
I have uploaded a [jupyter notebook](https://github.com/YoumiMa/dreeam/blob/main/heatmap_visualization.ipynb) for heatmap visualization. Our visualization is based on another repository [here](https://github.com/jiesutd/Text-Attention-Heatmap-Visualization). 
Please make sure to modify several hard-coded file paths in the notebook.

I hope this update can solve your problem, thanks!

**Comment by edwarddiou** [comment]
Thanks for the reply.
非常感謝
![擷取](https://github.com/YoumiMa/dreeam/assets/63232802/ba8241e6-c3bc-4305-b765-d24323bcf3f4)
![image](https://github.com/YoumiMa/dreeam/assets/63232802/9f423573-35be-4e46-a4d8-148ee0562dd0)

能否再請教一下，paper中的BERT版本和RoberTa 版本的DREEAM (teacher)與加上Inference-stage Fusion，是使用scripts/run_bert.sh 的參數並訓練30 epoch就可達到的嗎?  還是需要訓練更多epoch呢?

非常感謝您的答覆

**Comment by YoumiMa** [comment]
@edwarddiou 感謝您的回覆。
直接使用`scripts/run_bert.sh`與`scripts/run_roberta.sh`的參數應該就可以達到您截圖中第一行與第三行的性能。如果您想要再現inference-stage fusion的性能，請在模型訓練完成之後運行`scripts/isf_bert.sh`與`scripts/isf_roberta.sh`。

希望這能解決您的問題。謝謝！
