### ISSUE TITLE
About the experiment on Re-DocRED

### ISSUE THREAD

**Issue by Jize-W** [YoumiMa/dreeam#11]
Which script should I run for the experiment in Table 6:
DREEAM+Inference-Stage Fusion, without Distantly-Supervised Data (F1 80.73; Ign F1 79.66) ?

**Comment by YoumiMa** [comment]
Hi @Jize-W, thank you for your interest in this project.
Sorry for the missing instruction. To train a model on Re-DocRED, the parameters should be basically the same as DocRED.
Specifically, please:
1. Download [Re-DocRED](https://github.com/tonytan48/Re-DocRED) and place the files (`[train|dev|test]_revised.json`) under the same directory of docred (i.e., `dataset/docred`);
2. Change the `--train_file`, `--dev_file`, `--test_file` arguments accordingly in [scripts/run_roberta.sh](https://github.com/YoumiMa/dreeam/blob/main/scripts/run_roberta.sh) and [scripts/isf_roberta.sh](https://github.com/YoumiMa/dreeam/blob/main/scripts/isf_roberta.sh);
3. Train the model using the command: `bash scripts/run_roberta.sh ${name} 0.05 ${seed}`;
4. After the model is trained, run isf using the command: `bash scripts/isf_roberta.sh ${name} ${model_dir} dev` for the development set and `bash scripts/isf_roberta.sh ${name} ${model_dir} train` for the test set.

I hope this is clear and solves your problem.

**Comment by Jize-W** [comment]
It works. Thanks a lot!
