### ISSUE TITLE
Guide to Fine-tuning

### ISSUE THREAD

**Issue by carrtesy** [YoumiMa/dreeam#12]
Hello,
Thanks for your great work. 

Can I ask a guide to fine-tune my own data for your model?
We plan to have dataset annotated with tagtog (https://www.tagtog.com/).
Format is as follows (in json)

```json
{
"entities":[
{"classId":"e_6","part":"s1v1","offsets":[{"start":32,"text":"..."}],},
], 
"relations":
[
{"classId":"r_7"
"entities":["s1v1|e_1|129,134","s1v1|e_2|138,141"],
]
}
```

r_7 is relation id, and e_1 and e_2 are entity id. (129,134) and (138,141) is span index. 

We plan to have train and test file with above mentioned json structure.
Could you give us a guide for this?

Thanks in advance!

**Comment by YoumiMa** [comment]
Hi @carrtesy, thanks for your interest in this project!

To fine-tune (train?) DREEAM on your dataset, I see a necessity to write a script for converting the data structure into something similar to [DocRED](https://github.com/thunlp/DocRED/tree/master/data).
As introduced in the repo above, the data format should be:

```
{
  'title',
  'sents':     [
                  [word in sent 0],
                  [word in sent 1]
               ]
  'vertexSet': [
                  [
                    { 'name': mention_name, 
                      'sent_id': mention in which sentence, 
                      'pos': position of mention in a sentence, 
                      'type': NER_type}
                    {anthor mention}
                  ], 
                  [another entity]
                ]
  'labels':   [
                {
                  'h': idx of head entity in vertexSet,
                  't': idx of tail entity in vertexSet,
                  'r': relation,
                  'evidence': evidence sentences' id
                }
              ]
}
```

You can also download DocRED to take a closer look at the data format.

I hope this is clear and helps you solve your problem.

**Comment by carrtesy** [comment]
Thanks a lot for your kind reply, I appreciate your help!
Have a wonderful day!
