### ISSUE TITLE
I am unsure if this is a bug or not

### ISSUE THREAD

**Issue by WilliamAntoniocrayon** [YoumiMa/dreeam#14]
Hi, I found a bug while executing step3.  Readme.md states that the final output of step3 will be saved in `${name}_lambda${lambda}/${timestamp}/`, but you don't seem to add this directive to `NAME=${TYPE}_lambda${LAMBDA} `in the script `run_self_train_bert.sh`. The final result of step3 is saved in `./step3/2023-06-25_18:31:33.398134/`

**Comment by YoumiMa** [comment]
Hi @WilliamAntoniocrayon , thanks for the report.
I believe the inconsistency should have been fixed at commit [e9ef62d](https://github.com/YoumiMa/dreeam/commit/e9ef62de170478d640002531ca6a3e3fbc748fe4). please let me know if it is not.

**Comment by WilliamAntoniocrayon** [comment]
It's okay that I re-run, thank you very much for your help
