### ISSUE TITLE
Publish checkpoints

### ISSUE THREAD

**Issue by jonathanforking** [YoumiMa/dreeam#16]
Hi,
I would like to use your model for inference but lack the hardware necessary to train it (specifically the RoBERTa version). Could you please share your checkpoints?

Thank you for your work

**Comment by YoumiMa** [comment]
Hi @jonathanforking , thanks for your interest in this project!

Sorry for the late reply. We have uploaded the checkpoints in commit cf820ae78c48746c1341011250c65b7271435b69. Please let us know if you have a problem accessing the file.

**Comment by jonathanforking** [comment]
It works for me, thank you so much!
