### ISSUE TITLE
How many RAM does step2 need? step2 到底需要多少内存？

### ISSUE THREAD

**Issue by Winson-Huang** [YoumiMa/dreeam#17]
与 issue #9 一样，我也遇到了在 step2 中出现进程被杀死的情况，可以定位到代码行是 [run.py#L161](https://github.com/YoumiMa/dreeam/blob/cf820ae78c48746c1341011250c65b7271435b69/run.py#L161)，大概率是您提到的内存不足的问题，但是我的实验环境有 125G RAM 可用，仍然不足，我比较好奇您使用的环境内存配置是怎样的？到底需要多少内存才可以一次性得到 attention 分数推理结果？

另外想了解下这套代码如果要改成多卡训练是否需要较多改动？

非常期待得到您的回复，十分感谢！

**Comment by YoumiMa** [comment]
@Winson-Huang 您好，感谢您对此项目的兴趣！

> 我比较好奇您使用的环境内存配置是怎样的？到底需要多少内存才可以一次性得到 attention 分数推理结果？

非常抱歉造成您的困扰。我们使用的实验环境有360G的CPU RAM可用。使用`htop`命令监视内存，可以发现step2最多占用的内存约为～220GB。由于train_distant.json中的样本数量较大，如果计算资源有限，这边有两个替代方案：
1. 先将train_distant.json拆做两份或者三份分别计算attention分数，最后再将多个文件结合在一起，以进行后续训练。每个文件保存的内容都是np.array的list，只需要将数个list的内容依序合并应该就可以。
2. 在run.py的L.158将保存的attention转换为float16形式：`attns.extend([a.to(torch.float16).cpu().numpy() for a in attn])`。请注意这可能会影响下一步操作的学习精度。https://github.com/YoumiMa/dreeam/blob/cf820ae78c48746c1341011250c65b7271435b69/run.py#L158 

> 另外想了解下这套代码如果要改成多卡训练是否需要较多改动？

我们并未尝试用多卡训练这套代码，所以这部分不是很确定。不过此项目本身并不会占用太多GPU内存，如果您使用bert做编码器，一枚16GB 的显卡应该就可以完成训练。

希望这些信息对您有帮助，谢谢！

**Comment by Winson-Huang** [comment]
好的，非常感谢
