### ISSUE TITLE
你好，是否能够预测实体？

### ISSUE THREAD

**Issue by lijiwen97** [YoumiMa/dreeam#18]
你好，在test过程中，test.json文件包含vertexSet，title和sents。若只给定文本sents，是否能够预测关系和实体？

**Comment by YoumiMa** [comment]
@lijiwen97 您好，感谢您对本项目的兴趣！

本项目只针对给定文本以及实体，预测关系的情况而设计。
如果只给定文本，需要先使用其他的工具从文本中预测实体，再将文本与预测出的实体一同作为输入提供给我们的模型进行关系预测。

希望这能解决您的问题，谢谢！
