### ISSUE TITLE
the score is 0 when I use it for test evaluation

### ISSUE THREAD

**Issue by wucui5** [YoumiMa/dreeam#19]
"Hello, when I use your model to run the Fully-supervised setting, the score is normal in the first step. It's also normal when I use it for dev evaluation. However, the score is 0 when I use it for test evaluation. The first step command is 'dreeamfusion 0.1 66', and the script is:

```
TYPE=$1
LAMBDA=$2
SEED=$3

NAME=${TYPE}_lambda${LAMBDA}

python run.py --do_train \
--data_dir dataset/docred \
--transformer_type bert \
--model_name_or_path bert-base-cased \
--display_name ${NAME} \
--save_path ${NAME} \
--train_file train_annotated.json \
--dev_file dev.json \
--train_batch_size 4 \
--test_batch_size 8 \
--gradient_accumulation_steps 1 \
--num_labels 4 \
--lr_transformer 5e-5 \
--max_grad_norm 1.0 \
--evi_thresh 0.2 \
--evi_lambda ${LAMBDA} \
--warmup_ratio 0.06 \
--num_train_epochs 50.0 \
--seed ${SEED} \
--num_class 97
```

The second step is to evaluate dev, the command is 'bash scripts/isf_bert.sh testfusion dreeamfusion_lambda0.1/2023-11-18_14:07:31.394218 dev', the result is a normal score, and the script is:

```
NAME=$1
MODEL_DIR=$2
SPLIT=$3

python run.py --data_dir dataset/docred \
--transformer_type bert \
--model_name_or_path bert-base-cased \
--display_name  ${NAME} \
--load_path ${MODEL_DIR} \
--eval_mode fushion \
--test_file ${SPLIT}.json \
--test_batch_size 8 \
--num_labels 4 \
--evi_thresh 0.2 \
--num_class 97
```

Then I conducted the test evaluation. At this time, there is a 'thresh' file in the 'dreeamfusion_lambda0.1/2023-11-18_14:07:31.394218' directory, but the score that came out is all 0. Can you help me figure out what might be the reason?And moreover, I have made changes in the evaluate function as you have suggested.
<img width="945" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/31c4f8c6-926a-49f2-9517-2dfdbb5f5dde">
<img width="905" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/efa4b92f-2e40-4b35-82a2-567cbbc5b3e0">
<img width="670" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/c33c1506-d049-4626-b4c7-bc89780f0649">

**Comment by YoumiMa** [comment]
Hi @wucui5 , thank you for your interest in this project!
DocRED didn't release the gold labels for the test set. The file `test.json` in the directory `dataset/docred` contains only sentences and entities of each document but not the relations. Evaluating the performance on the test set locally thus compares the predicted results against an empty relation set, resulting in a score of 0.

To obtain the evaluation scores on the test set, please rename `fused_results.json` into `result.json`, compress it as a zip file named `result.zip`, and submit the zip file to the official evaluation site of DocRED: https://codalab.lisn.upsaclay.fr/competitions/365#learn_the_details-submission-format

I hope this is clear and resolves your concern.

**Comment by wucui5** [comment]
> Hi @wucui5 , thank you for your interest in this project! DocRED didn't release the gold labels for the test set. The file `test.json` in the directory `dataset/docred` contains only sentences and entities of each document but not the relations. Evaluating the performance on the test set locally thus compares the predicted results against an empty relation set, resulting in a score of 0.
> 
> To obtain the evaluation scores on the test set, please rename `fused_results.json` into `result.json`, compress it as a zip file named `result.zip`, and submit the zip file to the official evaluation site of DocRED: https://codalab.lisn.upsaclay.fr/competitions/365#learn_the_details-submission-format
> 
> I hope this is clear and resolves your concern.

I've uploaded a file and received a evidence score of 0. I found that my fusion_result.json file doesn't contain any evidence sentences. Is this normal? 
<img width="332" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/653b1a0b-e490-47af-b037-8aad6ea63f77">
<img width="662" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/fa351581-4547-463b-aed8-7c9a40f414df">

**Comment by YoumiMa** [comment]
Hi, @wucui5,

> I found that my fusion_result.json file doesn't contain any evidence sentences. Is this normal?

Yes, this is normal because the second round of inference (triggered by argument `--eval_mode fushion`) only performs relation extraction. If you would like to know the performance of evidence retrieval, please submit the predicted results of the first round, i.e., the file named `results.json` to Colab. Also, please remember to change the filename and zip the file as required.

I hope this is clear and answers your question.

A similar issue:  https://github.com/YoumiMa/dreeam/issues/6

**Comment by wucui5** [comment]
> Hi, @wucui5,
> 
> > I found that my fusion_result.json file doesn't contain any evidence sentences. Is this normal?
> 
> Yes, this is normal because the second round of inference (triggered by argument `--eval_mode fushion`) only performs relation extraction. If you would like to know the performance of evidence retrieval, please submit the predicted results of the first round, i.e., the file named `results.json` to Colab. Also, please remember to change the filename and zip the file as required.
> 
> I hope this is clear and answers your question.
> 
> A similar issue: #6

Thank you very much for your help. If there is no evidence in the result file after the test, then where did the test eviF1 get from the result file in your paper? Also, I would like to ask you whether the dev score in the paper is obtained during the first stage of training or at the time of assessment. The score that I reproduced was about 61.8 during training and about 62.5 during assessment.

**Comment by YoumiMa** [comment]
Hi @wucui5, thanks for the reply.
> If there is no evidence in the result file after the test, then where did the test eviF1 get from the result file in your paper?

We reported the evidence score based on predictions from the **first** round of inference, i.e., predictions in `results.json“. I believe you can find evidence predictions in that file. 

>  whether the dev score in the paper is obtained during the first stage of training or at the time of assessment.

We reported both results in the paper with two separate lines. The first line shows the scores in the first stage and the second line shows the scores after the fashion (i.e., the line with `+ Inference-stage Fusion`). I think you've successfully reproduced results (61.8 of yours v.s. 61.42 in our paper, 62.5 v.s. 62.55 in our paper).

I hope these are clear and resolve your concern.

**Comment by wucui5** [comment]
I want to run the RoBERTa model with full supervision, but the memory is insufficient. Therefore, I've downloaded your published file, roberta_teacher_best.ckpt (checkpoint after fully supervised training), intending to directly use it for testing. However, I encountered an error during the test. The command I ran was bash scripts/isf_roberta.sh devtest roberta_lambda0.1/installation dev, and the script is:

NAME=
1
�
�
�
�
�
�
�
�
=
1MODEL 
D
​
 IR=2
SPLIT=$3

python run.py --data_dir dataset/docred
--transformer_type roberta
--model_name_or_path roberta-large
--display_name 
�
�
�
�
 
−
−
�
�
�
�
�
�
�
ℎ
NAME −−load 
p
​
 ath{MODEL_DIR}
--eval_mode fushion
--test_file ${SPLIT}.json
--test_batch_size 8
--num_labels 4
--evi_thresh 0.2
--num_class 97

Can this checkpoint not be directly used for testing?
<img width="1145" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/df7fffbc-a916-4e29-be70-cf4b833f38f1">
<img width="213" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/28bce100-ccf1-4e54-b77e-c73fefd4dc2c">
"This is your checkpoint file I downloaded, I've put it in the installation folder."

**Comment by YoumiMa** [comment]
Hi @wucui5 , I re-checked and succeeded in performing inference with the distributed checkpoint `roberta_teacher_best.ckpt`.

Command: `bash scripts/isf_roberta.sh devtest roberta_teacher/ dev`

Output:
```
wandb: Currently logged in as: youmima (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.16.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.14
wandb: Run data is saved locally in /home/ma.y/Research/dreeam/wandb/run-20231120_172611-32youh77
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run devtest
wandb: ⭐️ View project at https://wandb.ai/youmima/DocRED
wandb: 🚀 View run at https://wandb.ai/youmima/DocRED/runs/32youh77
Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading examples: 100%|███████████████████████| 998/998 [00:17<00:00, 57.05it/s]
# of documents 998.
# of positive examples 11470.
# of negative examples 384102.
Evaluating batches: 100%|█████████████████████| 125/125 [00:21<00:00,  5.70it/s]
preds: 100%|██████████████████████████| 395572/395572 [00:53<00:00, 7424.14it/s]
saving official predictions into ../docre/roberta_teacher/results.json ...
saving evaluations into ../docre/roberta_teacher/dev_scores.csv ...
              precision     recall         F1
test_rel      67.460100  60.260692  63.657487
test_rel_ign  63.562091  60.260692  61.867381
test_evi      61.485387  48.548080  54.256175
saving topk results into ../docre/roberta_teacher/topk_results.json ...

wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     dev_F1 ▁
wandb: dev_F1_ign ▁
wandb: dev_evi_F1 ▁
wandb: 
wandb: Run summary:
wandb:     dev_F1 63.65749
wandb: dev_F1_ign 61.86738
wandb: dev_evi_F1 54.25617

wandb: 
wandb: Synced devtest: https://wandb.ai/youmima/DocRED/runs/32youh77
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231120_172611-32youh77/logs
wandb: Currently logged in as: youmima (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.16.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.14
wandb: Run data is saved locally in /home/ma.y/Research/dreeam/wandb/run-20231120_172817-bmu9z2p8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run devtest
wandb: ⭐️ View project at https://wandb.ai/youmima/DocRED
wandb: 🚀 View run at https://wandb.ai/youmima/DocRED/runs/bmu9z2p8
Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.layer_norm.weight', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Loading examples: 100%|████████████████████████████████████████████████████████████████| 998/998 [00:17<00:00, 55.61it/s]
# of documents 998.
# of positive examples 11470.
# of negative examples 384102.
Loading examples: 100%|████████████████████████████████████████████████████████████████| 998/998 [00:47<00:00, 20.90it/s]
# of documents 35874.
# of positive examples 132076.
# of negative examples 2367266.
Evaluating batches: 100%|████████████████████████████████████████████████████████████| 4485/4485 [03:16<00:00, 22.83it/s]
preds: 100%|████████████████████████████████████████████████████████████████| 2499342/2499342 [03:28<00:00, 11962.45it/s]
Best thresh 0.5277681350708008 	best F1 0.6457787
saving official predictions into ../docre/roberta_teacher/fused_results.json ...
saving evaluations into ../docre/roberta_teacher/dev_fused_scores.csv ...
             precision     recall         F1
dev_rel      65.997619  63.217923  64.577872
dev_rel_ign  62.089892  63.217923  62.648830
dev_evi       0.000000   0.000000   0.000000
saving threshold into ../docre/roberta_teacher/thresh ...

wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:     dev_F1 ▁
wandb: dev_F1_ign ▁
wandb: dev_evi_F1 ▁
wandb: 
wandb: Run summary:
wandb:     dev_F1 64.57787
wandb: dev_F1_ign 62.64883
wandb: dev_evi_F1 0
wandb: 
wandb: Synced devtest: https://wandb.ai/youmima/DocRED/runs/bmu9z2p8
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231120_172817-bmu9z2p8/logs
```

Given that the error comes from loading the model weights, I suspect there is a version mismatch of the package on your machine. Could you please downgrade/upgrade the `transformers` package to version `4.14.1` and rerun the bash script?

**Comment by wucui5** [comment]
> Hi @wucui5 , I re-checked and succeeded in performing inference with the distributed checkpoint `roberta_teacher_best.ckpt`.
> 
> Command: `bash scripts/isf_roberta.sh devtest roberta_teacher/ dev`
> 
> Output:
> 
> ```
> wandb: Currently logged in as: youmima (use `wandb login --relogin` to force relogin)
> wandb: wandb version 0.16.0 is available!  To upgrade, please run:
> wandb:  $ pip install wandb --upgrade
> wandb: Tracking run with wandb version 0.12.14
> wandb: Run data is saved locally in /home/ma.y/Research/dreeam/wandb/run-20231120_172611-32youh77
> wandb: Run `wandb offline` to turn off syncing.
> wandb: Syncing run devtest
> wandb: ⭐️ View project at https://wandb.ai/youmima/DocRED
> wandb: 🚀 View run at https://wandb.ai/youmima/DocRED/runs/32youh77
> Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.bias', 'lm_head.dense.bias', 'lm_head.decoder.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias']
> - This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Loading examples: 100%|███████████████████████| 998/998 [00:17<00:00, 57.05it/s]
> # of documents 998.
> # of positive examples 11470.
> # of negative examples 384102.
> Evaluating batches: 100%|█████████████████████| 125/125 [00:21<00:00,  5.70it/s]
> preds: 100%|██████████████████████████| 395572/395572 [00:53<00:00, 7424.14it/s]
> saving official predictions into ../docre/roberta_teacher/results.json ...
> saving evaluations into ../docre/roberta_teacher/dev_scores.csv ...
>               precision     recall         F1
> test_rel      67.460100  60.260692  63.657487
> test_rel_ign  63.562091  60.260692  61.867381
> test_evi      61.485387  48.548080  54.256175
> saving topk results into ../docre/roberta_teacher/topk_results.json ...
> 
> wandb: Waiting for W&B process to finish... (success).
> wandb:                                                                                
> wandb: 
> wandb: Run history:
> wandb:     dev_F1 ▁
> wandb: dev_F1_ign ▁
> wandb: dev_evi_F1 ▁
> wandb: 
> wandb: Run summary:
> wandb:     dev_F1 63.65749
> wandb: dev_F1_ign 61.86738
> wandb: dev_evi_F1 54.25617
> 
> wandb: 
> wandb: Synced devtest: https://wandb.ai/youmima/DocRED/runs/32youh77
> wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
> wandb: Find logs at: ./wandb/run-20231120_172611-32youh77/logs
> wandb: Currently logged in as: youmima (use `wandb login --relogin` to force relogin)
> wandb: wandb version 0.16.0 is available!  To upgrade, please run:
> wandb:  $ pip install wandb --upgrade
> wandb: Tracking run with wandb version 0.12.14
> wandb: Run data is saved locally in /home/ma.y/Research/dreeam/wandb/run-20231120_172817-bmu9z2p8
> wandb: Run `wandb offline` to turn off syncing.
> wandb: Syncing run devtest
> wandb: ⭐️ View project at https://wandb.ai/youmima/DocRED
> wandb: 🚀 View run at https://wandb.ai/youmima/DocRED/runs/bmu9z2p8
> Some weights of the model checkpoint at roberta-large were not used when initializing RobertaModel: ['lm_head.layer_norm.weight', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.dense.bias']
> - This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Loading examples: 100%|████████████████████████████████████████████████████████████████| 998/998 [00:17<00:00, 55.61it/s]
> # of documents 998.
> # of positive examples 11470.
> # of negative examples 384102.
> Loading examples: 100%|████████████████████████████████████████████████████████████████| 998/998 [00:47<00:00, 20.90it/s]
> # of documents 35874.
> # of positive examples 132076.
> # of negative examples 2367266.
> Evaluating batches: 100%|████████████████████████████████████████████████████████████| 4485/4485 [03:16<00:00, 22.83it/s]
> preds: 100%|████████████████████████████████████████████████████████████████| 2499342/2499342 [03:28<00:00, 11962.45it/s]
> Best thresh 0.5277681350708008 	best F1 0.6457787
> saving official predictions into ../docre/roberta_teacher/fused_results.json ...
> saving evaluations into ../docre/roberta_teacher/dev_fused_scores.csv ...
>              precision     recall         F1
> dev_rel      65.997619  63.217923  64.577872
> dev_rel_ign  62.089892  63.217923  62.648830
> dev_evi       0.000000   0.000000   0.000000
> saving threshold into ../docre/roberta_teacher/thresh ...
> 
> wandb: Waiting for W&B process to finish... (success).
> wandb:                                                                                
> wandb: 
> wandb: Run history:
> wandb:     dev_F1 ▁
> wandb: dev_F1_ign ▁
> wandb: dev_evi_F1 ▁
> wandb: 
> wandb: Run summary:
> wandb:     dev_F1 64.57787
> wandb: dev_F1_ign 62.64883
> wandb: dev_evi_F1 0
> wandb: 
> wandb: Synced devtest: https://wandb.ai/youmima/DocRED/runs/bmu9z2p8
> wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
> wandb: Find logs at: ./wandb/run-20231120_172817-bmu9z2p8/logs
> ```
> 
> Given that the error comes from loading the model weights, I suspect there is a version mismatch of the package on your machine. Could you please downgrade/upgrade the `transformers` package to version `4.14.1` and rerun the bash script?

hi，After changing the version of the transformer library, I ran the command "bash scripts/isf_roberta.sh devtest roberta_teacher/ dev", but I still encountered an error.And the scripts is 
NAME=$1
MODEL_DIR=$2
SPLIT=$3

python run.py --data_dir dataset/docred \
--transformer_type roberta \
--model_name_or_path roberta-large \
--display_name  ${NAME} \
--load_path ${MODEL_DIR} \
--eval_mode single \
--test_file ${SPLIT}.json \
--test_batch_size 8 \
--num_labels 4 \
--evi_thresh 0.2 \
--num_class 97

python run.py --data_dir dataset/docred \
--transformer_type roberta \
--model_name_or_path roberta-large \
--display_name  ${NAME} \
--load_path ${MODEL_DIR} \
--eval_mode fushion \
--test_file ${SPLIT}.json \
--test_batch_size 8 \
--num_labels 4 \
--evi_thresh 0.2 \
--num_class 97
<img width="841" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/3a15bda8-20fe-4679-8e07-a3ac0942ca14">
<img width="857" alt="image" src="https://github.com/YoumiMa/dreeam/assets/131764970/e93c3a72-28eb-4eac-9a26-ec4aaa4aa450">

**Comment by YoumiMa** [comment]
Hi @wucui5 , the error `BrokenPipeError: [Error 32] Broken pipe` basically indicates a connectivity problem between the client and the server. I intuitively have a feeling that the error only occurs occasionally. Please re-run the script and see if you can reproduce the error. If the error can be reproduced, try disabling wandb using the command `wandb offline` before running the script. That could work by avoiding the client-server communication of wandb. 

The error `FileNotFoundError` happened because the first part of ISF didn't complete. If the `BrokenPipeError` is resolved, the `FileNotFoundError` should disappear.
