### ISSUE TITLE
baseline模型E2GRE

### ISSUE THREAD

**Issue by YjwHello** [YoumiMa/dreeam#2]
请问您知道E2GRE模型的GitHub地址吗？谢谢

**Comment by YoumiMa** [comment]
@YjwHello 您好，感谢您的提问。
很遗憾，我并不知道E2GRE项目的Github地址在哪里。或许您可以发邮件询问该项目的作者。
非常抱歉没能帮上您的忙。

**Comment by YjwHello** [comment]
谢谢，我给作者发了邮件
