### ISSUE TITLE
`scripts/run_finetune_roberta.sh` runs `train.py` (not a file)

### ISSUE THREAD

**Issue by Dylan-Gallagher** [YoumiMa/dreeam#20]
When fine-tuning, the script `run_finetune_roberta.sh` runs `train.py` and gets an error, as that doesn't exist.

Should it run `run.py` instead?

**Comment by YoumiMa** [comment]
Hi @Dylan-Gallagher,

Thank you for your interest in this project!
Yes, it was a typo and should be `run.py`. I have fixed it in the commit [476a700](https://github.com/YoumiMa/dreeam/commit/476a7004521d5f9b7bb3be66fc6678495b3cf291).
Thank you so much for pointing it out!

**Comment by Dylan-Gallagher** [comment]
Thank you very much. I appreciate your ongoing support of this project. I find it very useful for my studies.
