### ISSUE TITLE
Problem correction

### ISSUE THREAD

**Issue by maoxuxu** [YoumiMa/dreeam#22]
Dear author, the first data of KD DocRE-BERT base in Table 2 of this article may have been mistakenly written as KD DocRE-NA-RoBERT large.Thank you again for the author's research.

**Comment by YoumiMa** [comment]
Hi @maoxuxu , thank you for your interest in this project!
We truly appreciate you for pointing it out. The data should be 62.62 instead of 63.38. 
We will probably fix it in a future version.
