### ISSUE TITLE
可以将模型换成大语言模型运行吗？

### ISSUE THREAD

**Issue by Icamd** [YoumiMa/dreeam#24]
您好，感谢您出色的工作！我想请教一下，有可能能将您的算法框架用在大语言模型上吗？如果可以的话，应该修改哪部分的代码，以保留读取DocRed和Re-DocRed数据集部分和测试结果F1输出部分呢？感谢！

**Comment by YoumiMa** [comment]
@Icamd 您好，感谢您对本项目的兴趣！
非常抱歉，我们并未实现本算法框架在大语言模型上的运用。本算法框架需要以编码器语言模型作为骨架，而GPT等大语言模型为解码器模型，因此我们认为要将二者融合可能会存在一些困难。

**Comment by Icamd** [comment]
@YoumiMa 明白了，谢谢您
