### ISSUE TITLE
num_labels=4为什么

### ISSUE THREAD

**Issue by 18410080631** [YoumiMa/dreeam#26]
您好，在看代码的过程中我不太理解num_labels=4的含义，这个变量是为了什么

**Comment by YoumiMa** [comment]
@18410080631 您好，感谢您对本项目的兴趣！

`num_labels=4` 是指针对任一实体对$(e_1, e_2)$，可能预测的最大关系标签数量为4。也就是说，$(e_1,e_2)$之间最多可以有4种关系。

希望这能解决您的问题，谢谢！
