### ISSUE TITLE
save_attns

### ISSUE THREAD

**Issue by cuberJ** [YoumiMa/dreeam#3]
您好
我在step2下执行`infer_distant_bert.sh`的过程中，参数`--save_attn`在源码中我注意到传入的是空路径
接着在step3中执行脚本，传入参数`${teacher_signal_dir}`，然而整个项目中并没有找到`attn.pt`参数集，请问该目录或者`attn.pt`应该是位于哪里呢？
我试着在step2下将`${load_path}`设置为`--save_attn`的参数，但是执行就会报错，请问正确的操作应当是如何进行呢？

**Comment by YoumiMa** [comment]
@cuberJ 您好，感谢您对此项目的兴趣！

关于您的问题，`--save_attn`是一个二值变量，存在时表示True，不存在时表示False（参见`args.py`的第18行）。因此，无需向`--save_attn`传递任何路径或参数。
如果您执行`infer_distant_bert.sh`，那么在代码运行完成之后，`train_distant.attns`会被存储在`${load_dir}`目录下。关于`README.md`中对于`attn.pt`的记述，非常抱歉，这里存在一些笔误，我已经在最新的commit（`faf41db`）中修正这些笔误。

修正前：
> The command will perform an inference run on `train_distant.json` and record token importances as **`attns.pt`** saved under `${load_dir}`
> where `${name}` is the identifier of this run displayed in wandb, `${teacher_signal_dir} `is the directory that stores the **`attn.pt`** file, `${lambda}` is the scaler than controls the weight of evidence loss (see Eq. 13 in the paper), and `${seed} `is the value of random seed.

修正后：
>The command will perform an inference run on `train_distant.json` and record token importances as **`train_distant.attns`** saved under `${load_dir}`
> where `${name}` is the identifier of this run displayed in wandb, `${teacher_signal_dir}` is the directory that stores the **`train_distant.attns`** file, `${lambda}` is the scaler than controls the weight of evidence loss (see Eq. 13 in the paper), and `${seed}` is the value of random seed.

另外，请注意由于`train_distant.json`本身包含的数据较多，存储`train_distant.attns`可能会需要较大的空间。

希望这能解决您的问题。

**Comment by cuberJ** [comment]
感谢您的回复，在此还有两个小问题，不知可否解答一下：
1. 如您所说，`train_distant.attns`需要的空间较大，目前来看，对于内存的需求同样很高。由于牵涉实验器材购置问题，请问采用bert-base作为预训练模型的情况下，128GB内存是否适用于生成该参数集的计算过程？
2. 在step4中，传入的参数`student_model_dir`是否就是上一步中的`teacher_signal_dir`？

**Comment by YoumiMa** [comment]
@cuberJ 感谢您的提问。

1. 这边不确定您打算如何分配128GB的内存，所以无法给出确切的答案，但是`train_distant.attns`可能会占用50~70GB左右的内存。请注意这是对ROM的要求，而并非对RAM的要求。
2. `${student_model_dir}`并非`${teacher_signal_dir}`，因为student model的checkpoint是保存在与teacher model不同的目录下的。您可以自由定义`${student_model_dir}`的值。

希望这能回答您的问题。

**Comment by cuberJ** [comment]
好的好的，非常感谢
