### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by yxy0102** [YoumiMa/dreeam#6]
Hello, may I ask why I put the result.json of the teacher model training on the official website competition and the test results are all 0, and this model cannot train the remote supervised data set

**Comment by YoumiMa** [comment]
Hi @yxy0102 , thank you for contacting us!
1. [evaluation on Codalab] Please make sure the file you uploaded follows [instructions on Codalab](https://codalab.lisn.upsaclay.fr/competitions/365#learn_the_details-evaluation). Specifically, we should upload a zip file named `result.zip` compressed from a file named `result.json`. If this could not solve the problem, please provide us with the details of how you train the model and do the evaluation, including the script of each step.

2. [training on remotely (distantly?) supervised data] I’m sorry but more details are needed for us to identify the cause. Could you please provide us with more details? For example, if something such as an error message showed up, could you please share it with us?

**Comment by yxy0102** [comment]
In inference fusion verification, the prediction of evidence is always 0. What is the reason








?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YoumiMa/dreeam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YoumiMa/dreeam] wrong result (Issue #6)





 
Hi @yxy0102 , thank you for contacting us!
  
 
[evaluation on Codalab] Please make sure the file you uploaded follows instructions on Codalab. Specifically, we should upload a zip file named result.zip compressed from a file named result.json. If this could not solve the problem, please provide us with the details of how you train the model and do the evaluation, including the script of each step.
 
 
 
[training on remotely (distantly?) supervised data] I’m sorry but more details are needed for us to identify the cause. Could you please provide us with more details? For example, if something such as an error message showed up, could you please share it with us?

**Comment by YoumiMa** [comment]
@yxy0102 I assume that you are using `scripts/isf_bert.sh` provided in this repository. The script basically carries out two rounds of inference: the first round performs both relation extraction and evidence retrieval, and the second round performs only relation extraction (please refer to [our paper](https://arxiv.org/pdf/2302.08675.pdf) or [this paper ](https://arxiv.org/pdf/2106.08657.pdf)for more details). 
For this reason, the evaluation result on the second round of inference will not contain evidence predictions, thus yielding a score of zero for evidence evaluation. If you want to check the performance of evidence retrieval, please submit the predictions of the first round of inference.

I hope this is clear and solves your problem.
