### ISSUE TITLE
Error when exceeding max_seq_length

### ISSUE THREAD

**Issue by iden-alex** [YoumiMa/dreeam#7]
Thanks for the work. 
I applied the model to my Russian dataset, using the encoder model for Russian. Because of some documents in dataset are longer (token length and number of sentences) than in DocRED, at first I had got assert

```
assert len(sents) < max_seq_length
```
After commenting that assert I got

```Evaluating batches:  88% 21/24 [00:05<00:00,  3.97it/s]
Train epoch:   0% 0/20 [02:18<?, ?it/s]
Traceback (most recent call last):
  File "/content/drive/MyDrive/Models/dreeam/run.py", line 336, in <module>
    main()
  File "/content/drive/MyDrive/Models/dreeam/run.py", line 282, in main
    train(args, model, train_features, dev_features)
  File "/content/drive/MyDrive/Models/dreeam/run.py", line 123, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps)
  File "/content/drive/MyDrive/Models/dreeam/run.py", line 84, in finetune
    dev_scores, dev_output, official_results, results = evaluate(args, model, dev_features, tag="dev")
  File "/content/drive/MyDrive/Models/dreeam/run.py", line 141, in evaluate
    outputs = model(**inputs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/drive/MyDrive/Models/dreeam/model.py", line 228, in forward
    s_attn = self.forward_evi(doc_attn, sent_pos, batch_rel, offset)
  File "/content/drive/MyDrive/Models/dreeam/model.py", line 195, in forward_evi
    curr_sent_pos = [torch.arange(s[0], s[1]).to(curr_attn.device) + offset for s in sent_pos[i]] # + offset
  File "/content/drive/MyDrive/Models/dreeam/model.py", line 195, in <listcomp>
    curr_sent_pos = [torch.arange(s[0], s[1]).to(curr_attn.device) + offset for s in sent_pos[i]] # + offset
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I understand that the error is related to exceeding the max_seq_length. As a quick solution to obtain results, I defined the maximum text length in tokens in the dataset and increased the max_seq_length to 1500. 
However, I am concerned that this may affect the performance of the models (trying bert/roberta), and I would like to fix this error properly. 

It seems that I need to add truncating to the function [add_entity_markers](https://github.com/YoumiMa/dreeam/blob/main/prepro.py#L10) for sents. 
Can you help how to add text truncating here, considering that I also need to adjust the entity and relationship list accordingly?"

**Comment by YoumiMa** [comment]
Hi @iden-alex , thank you for the interest in our work!

To apply the model on documents longer than 1024 tokens, I'd suggest making some modifications on `long_seq.py`. The current codebase assumes each input document to be shorter than 1024 tokens. Documents with more than 512 tokens (but less than 1024 tokens) are truncated into two halves, one for the first 512 tokens and the other for the rest. In other words, tokens at the very beginning/end of the document will only be encoded once as they only appear in the first/second half, while tokens in between may be encoded twice as they may appear in both halves. The embedding of each token is computed as an average of its embedding(s) in the first and second half. 

Therefore, to encode a document longer than 1024,  say with a maximum length of 1500, it could be necessary to divide the document into three segments by modifying `long_seq.py`. 
Speaking of the entity and relationship list, I currently don't see a need to make any adjustments. During the encoding process, we split the document to ensure each segment contains less than 512 tokens. After the encoding process, operations are carried out document-wise with linear layers, having nothing to do with the length limitation of BERT/RoBERTa. 
Please let me know if you think differently.

I hope this is clear and helpful.

**Comment by iden-alex** [comment]
Thanks @YoumiMa ,  I think I missed it about chunks and long.seq.py. Now I have added a third chunk.

I also meant in the issue that truncation does not work in the model, because when the input text length is greater than max_seq_length=1024, I expect that there will be truncate to max_seq_length, but the model eventually falls. 
In what line can I add a truncate so that everything works correctly?

**Comment by YoumiMa** [comment]
Hi @iden-alex, 

I believe the truncation should be added in function `add_entity_markers()` in `prepro.py`. The function iterates through each sentence and adds an entity marker (`*`) before and after each entity mention to formulate the input sequence to the encoder. I can think of two kinds of implementations to add truncation:
1. stop iterating sentences when max sequence length is reached;
2. remove sentences or tokens that exceed the sequence length limitation. 

In both cases, please make sure to modify variables `sents` (recording the input document split into subwords), `sent_map` (recording the start/end position of each word), and `sent_pos` (recording the start/end position of each sentence). These modifications should help eliminate the error you've encountered before.

Please let me know if there are any further questions.
