### ISSUE TITLE
lambda value

### ISSUE THREAD

**Issue by CmwyAX** [YoumiMa/dreeam#8]
请问 为了复现论文中的结果；step3时lambda和seed应该设置为多少？

**Comment by YoumiMa** [comment]
@CmwyAX 您好，感谢您对本项目的兴趣！

本项目所有步骤均保持lambda值恒定。如果您使用的预训练语言模型是BERT(base)，请将lambda设置为0.1；如果您使用的预训练语言模型是RoBERTa(large)，请将lambda设置为0.05。我们在[论文的4.1节](https://arxiv.org/pdf/2302.08675.pdf)介绍了相关设置。您也可以在附录A找到更多关于参数设置的信息。

论文中所汇报的性能评价结果是多个模型的平均值。这些模型由不同的seed初始化，因此并不存在某个seed可以完美对应论文中的结果。您可以自由设定seed的值。

希望这能解决您的问题，谢谢！

**Comment by CmwyAX** [comment]
好的 谢谢您的解答
